// Code generated by MockGen. DO NOT EDIT.
// Source: githubapi.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGitHubApiClient is a mock of GitHubApiClient interface.
type MockGitHubApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubApiClientMockRecorder
}

// MockGitHubApiClientMockRecorder is the mock recorder for MockGitHubApiClient.
type MockGitHubApiClientMockRecorder struct {
	mock *MockGitHubApiClient
}

// NewMockGitHubApiClient creates a new mock instance.
func NewMockGitHubApiClient(ctrl *gomock.Controller) *MockGitHubApiClient {
	mock := &MockGitHubApiClient{ctrl: ctrl}
	mock.recorder = &MockGitHubApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubApiClient) EXPECT() *MockGitHubApiClientMockRecorder {
	return m.recorder
}

// CreatePullRequest mocks base method.
func (m *MockGitHubApiClient) CreatePullRequest(ctx context.Context, org, repo, headBranch, baseBranch, title, body string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequest", ctx, org, repo, headBranch, baseBranch, title, body)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockGitHubApiClientMockRecorder) CreatePullRequest(ctx, org, repo, headBranch, baseBranch, title, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockGitHubApiClient)(nil).CreatePullRequest), ctx, org, repo, headBranch, baseBranch, title, body)
}

// DeleteBranch mocks base method.
func (m *MockGitHubApiClient) DeleteBranch(ctx context.Context, org, repo, headBranch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranch", ctx, org, repo, headBranch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranch indicates an expected call of DeleteBranch.
func (mr *MockGitHubApiClientMockRecorder) DeleteBranch(ctx, org, repo, headBranch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranch", reflect.TypeOf((*MockGitHubApiClient)(nil).DeleteBranch), ctx, org, repo, headBranch)
}

// HealthCheck mocks base method.
func (m *MockGitHubApiClient) HealthCheck() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck")
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockGitHubApiClientMockRecorder) HealthCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockGitHubApiClient)(nil).HealthCheck))
}

// LabelPullRequest mocks base method.
func (m *MockGitHubApiClient) LabelPullRequest(ctx context.Context, org, repo string, prNum int, label string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LabelPullRequest", ctx, org, repo, prNum, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// LabelPullRequest indicates an expected call of LabelPullRequest.
func (mr *MockGitHubApiClientMockRecorder) LabelPullRequest(ctx, org, repo, prNum, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LabelPullRequest", reflect.TypeOf((*MockGitHubApiClient)(nil).LabelPullRequest), ctx, org, repo, prNum, label)
}
